# Generated by Django 5.0.4 on 2024-04-12 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_movie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='pics')),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('actor', models.CharField(max_length=233)),
                ('youtube', models.URLField()),
                ('added_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_movie.genres')),
            ],
        ),
    ]
