# Generated by Django 5.0.4 on 2024-04-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_movie', '0002_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='slug',
        ),
    ]
