# Generated by Django 5.0.4 on 2024-04-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_movie', '0003_remove_movies_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='slug',
            field=models.SlugField(default='hello', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
