# Generated by Django 5.0.4 on 2024-04-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_movie', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='slug',
            field=models.SlugField(max_length=342, null=True, unique=True),
        ),
    ]
